import Link from "next/link";
import type { OrganizationAnalytics } from "@/features/analytics/report";

const stages = ["APPLIED", "SCREENING", "SHORTLISTED", "ASSESSMENT", "INTERVIEW", "OFFER", "HIRED"];

function value(item: number | null, suffix = "") { return item === null ? "—" : `${item}${suffix}`; }
function dateInput(item: string | null) { return item?.slice(0, 10) ?? ""; }

export function AnalyticsWorkspace({ organizationId, organizationName, report, error }: { organizationId: string; organizationName: string; report: OrganizationAnalytics; error?: string }) {
  const maxStage = Math.max(1, ...stages.map((stage) => report.applications.byStage[stage] ?? 0));
  return <main className="workspace-main analytics-main"><div className="workspace-title"><div><p className="eyebrow">{organizationName}</p><h1>Analytics</h1><p>Operational visibility into hiring activity. These aggregates describe workflow; they do not rank candidates or make decisions.</p></div></div>
    {error && <p className="form-message error workspace-error" role="alert">{error}</p>}
    <section className="analytics-filter"><div><strong>Reporting period</strong><span>Filters use the record creation date and include both selected dates.</span></div><form method="get"><label>From<input name="from" type="date" defaultValue={dateInput(report.range.from)} /></label><label>To<input name="to" type="date" defaultValue={dateInput(report.range.to)} /></label><button className="button primary" type="submit">Apply</button><Link className="button ghost" href={`/dashboard/organizations/${organizationId}/analytics`}>All time</Link></form></section>
    <section className="analytics-metrics"><article><span>Applications</span><strong>{report.applications.total}</strong><small>{report.candidates.total} candidates added</small></article><article><span>Interviews</span><strong>{report.interviews.total}</strong><small>{report.interviews.byStatus.COMPLETED ?? 0} completed</small></article><article><span>Offers</span><strong>{report.offers.total}</strong><small>{report.offers.byStatus.ACCEPTED ?? 0} accepted</small></article><article><span>Evidence records</span><strong>{report.evidence.total}</strong><small>{report.resumes.total} resumes uploaded</small></article></section>
    <section className="analytics-insights"><article><span>Offer acceptance</span><strong>{value(report.insights.offerAcceptanceRate, "%")}</strong><p>Accepted offers divided by accepted and declined offers. Pending and withdrawn offers are excluded.</p></article><article><span>Interview completion</span><strong>{value(report.insights.interviewCompletionRate, "%")}</strong><p>Completed interviews divided by all interviews created during this period.</p></article><article><span>Resumes per candidate</span><strong>{value(report.insights.resumesPerCandidate)}</strong><p>Uploaded resumes divided by candidates added during this period.</p></article><article><span>Evidence per candidate</span><strong>{value(report.insights.evidencePerCandidate)}</strong><p>Reviewer-recorded evidence divided by candidates added during this period.</p></article></section>
    <div className="analytics-grid"><section className="analytics-panel"><header><div><p className="eyebrow">Current position</p><h2>Application stages</h2></div><strong>{report.applications.total}</strong></header>{report.applications.total ? <div className="stage-bars">{stages.map((stage) => { const count = report.applications.byStage[stage] ?? 0; return <div key={stage}><span>{stage.replaceAll("_", " ").toLowerCase()}</span><i><b style={{ width: `${(count / maxStage) * 100}%` }} /></i><strong>{count}</strong></div>; })}</div> : <p className="analytics-empty">No applications were created in this period.</p>}</section>
      <section className="analytics-panel"><header><div><p className="eyebrow">Workload</p><h2>Applications by job</h2></div><strong>{report.jobs.total}</strong></header>{report.applicationsByJob.length ? <div className="job-analytics-list">{report.applicationsByJob.map((job) => <article key={job.id}><div><strong>{job.title}</strong><span>{Object.entries(job.byStage).map(([stage, count]) => `${count} ${stage.toLowerCase()}`).join(" / ")}</span></div><b>{job.total}</b></article>)}</div> : <p className="analytics-empty">No job activity was recorded in this period.</p>}</section></div>
    <p className="human-decision-note analytics-note">Analytics are descriptive and may be affected by the selected creation-date window. Hiring decisions must remain evidence-based and human-controlled.</p></main>;
}
