import Link from "next/link";
import type { OrganizationAuditLog } from "@/features/audit/report";

function label(value: string) { return value.replaceAll("_", " ").toLowerCase(); }
function metadata(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return []; return Object.entries(value as Record<string, unknown>).filter(([, item]) => typeof item === "string"); }

export function AuditWorkspace({ organizationId, organizationName, logs, filters, error }: { organizationId: string; organizationName: string; logs: OrganizationAuditLog[]; filters: { action?: string; entityType?: string; entityId?: string }; error?: string }) {
  return <main className="workspace-main audit-main"><div className="workspace-title"><div><p className="eyebrow">{organizationName}</p><h1>Audit log</h1><p>Review attributable hiring and access-control events. Audit records are append-only and cannot be edited here.</p></div></div>{error && <p className="form-message error workspace-error" role="alert">{error}</p>}
    <section className="audit-filter"><form method="get"><label>Action<input name="action" maxLength={100} defaultValue={filters.action} placeholder="OFFER_ACCEPTED" /></label><label>Entity type<input name="entityType" maxLength={100} defaultValue={filters.entityType} placeholder="Offer" /></label><label>Entity ID<input name="entityId" maxLength={100} defaultValue={filters.entityId} placeholder="UUID" /></label><button className="button primary" type="submit">Filter</button><Link className="button ghost" href={`/dashboard/organizations/${organizationId}/audit`}>Clear</Link></form></section>
    <section className="audit-timeline">{logs.length ? logs.map((log) => <article key={log.id}><i aria-hidden="true" /><div><header><div><strong>{label(log.action)}</strong><span>{log.entityType}</span></div><time>{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(log.createdAt)}</time></header><p>{log.actor?.email ?? "System or deleted user"}</p><code>{log.entityId}</code>{metadata(log.metadata).length > 0 && <dl>{metadata(log.metadata).map(([key, value]) => <div key={key}><dt>{label(key)}</dt><dd>{String(value)}</dd></div>)}</dl>}</div></article>) : <div className="panel-empty">No audit events match these filters.</div>}</section><p className="human-decision-note audit-note">Audit history supports accountability. It does not replace evidence review or authorize a hiring decision.</p></main>;
}
