"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { responseError } from "./auth-form";

type AssessmentSummary = { id: string; title: string; durationMinutes: number; status: string; submission: { status: "DRAFT" | "SUBMITTED"; startedAt: string; submittedAt: string | null } | null };
type OfferSummary = { id: string; title: string; status: string; expiresAt: string | null } | null;
type Application = { id: string; currentStage: string; createdAt: string; job: { id: string; title: string; description: string }; codingAssessments: AssessmentSummary[]; offer: OfferSummary };
type Question = { id: string; prompt: string; language: string | null; starterCode: string | null; points: number; position: number };
type AssessmentDetail = { id: string; title: string; instructions: string; durationMinutes: number; questions: Question[] };
type Submission = { status: "DRAFT" | "SUBMITTED"; answersJson: Record<string, string>; startedAt: string; submittedAt: string | null };
type Offer = { id: string; title: string; details: string; compensationDetails: string | null; expiresAt: string | null; status: string; responseNote: string | null };

export function secondsRemaining(startedAt: string, durationMinutes: number, now = Date.now()) { return Math.max(0, Math.floor((new Date(startedAt).getTime() + durationMinutes * 60_000 - now) / 1000)); }
function stageLabel(stage: string) { return stage.replaceAll("_", " ").toLowerCase(); }

export function CandidatePortal({ organizationId, organizationName, candidate, applications }: { organizationId: string; organizationName: string; candidate: { name: string; email: string }; applications: Application[] }) {
  const router = useRouter(); const [openAssessment, setOpenAssessment] = useState<{ applicationId: string; assessment: AssessmentDetail; submission: Submission | null } | null>(null); const [openOffer, setOpenOffer] = useState<{ applicationId: string; offer: Offer } | null>(null); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function json(path: string, options: RequestInit = {}) { setBusy(path); setError(""); setMessage(""); try { const response = await fetch(path, options); if (!response.ok) { setError(await responseError(response)); return null; } return await response.json(); } catch { setError("The service is unavailable. Try again shortly."); return null; } finally { setBusy(""); } }
  async function loadAssessment(applicationId: string, assessmentId: string) { const path=`/api/portal/organizations/${organizationId}/applications/${applicationId}/assessments/${assessmentId}`; const body=await json(path); if(body) setOpenAssessment({applicationId,assessment:body.assessment,submission:body.submission}); }
  async function startAssessment(applicationId: string, assessmentId: string) { const path=`/api/portal/organizations/${organizationId}/applications/${applicationId}/assessments/${assessmentId}`; const started=await json(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status:"DRAFT",answers:{}})}); if(started) await loadAssessment(applicationId,assessmentId); }
  async function saveSubmission(event: FormEvent<HTMLFormElement>, status: "DRAFT" | "SUBMITTED") { event.preventDefault(); if(!openAssessment)return; const form=new FormData(event.currentTarget),answers=Object.fromEntries(openAssessment.assessment.questions.map(q=>[q.id,String(form.get(q.id)??"")])); const path=`/api/portal/organizations/${organizationId}/applications/${openAssessment.applicationId}/assessments/${openAssessment.assessment.id}`; const body=await json(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status,answers})}); if(body){setMessage(status==="SUBMITTED"?"Assessment submitted. Your answers are now final.":"Draft saved.");router.refresh();await loadAssessment(openAssessment.applicationId,openAssessment.assessment.id);} }
  async function loadOffer(applicationId:string){const body=await json(`/api/portal/organizations/${organizationId}/applications/${applicationId}/offer`);if(body)setOpenOffer({applicationId,offer:body.offer});}
  async function respondOffer(event:FormEvent<HTMLFormElement>,status:"ACCEPTED"|"DECLINED"){event.preventDefault();if(!openOffer)return;const form=new FormData(event.currentTarget),body=await json(`/api/portal/organizations/${organizationId}/applications/${openOffer.applicationId}/offer`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status,responseNote:form.get("responseNote")})});if(body){setOpenOffer({applicationId:openOffer.applicationId,offer:body.offer});setMessage(`Offer ${status.toLowerCase()}.`);router.refresh();}}
  return <main className="portal-main"><header className="portal-welcome"><div><p className="eyebrow">{organizationName} candidate portal</p><h1>Welcome, {candidate.name}.</h1><p>Track your applications and complete assigned actions. Hiring decisions are made by the hiring team.</p></div><span>{candidate.email}</span></header>{error&&<p className="form-message error" role="alert">{error}</p>}{message&&<p className="form-message success" role="status">{message}</p>}<section className="portal-applications">{applications.map(application=><article key={application.id}><header><div><span className="portal-stage">{stageLabel(application.currentStage)}</span><h2>{application.job.title}</h2><p>{application.job.description}</p></div><time>Applied {new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(application.createdAt))}</time></header><div className="portal-actions"><section><h3>Assessments</h3>{application.codingAssessments.length?application.codingAssessments.map(assessment=><div className="portal-action-row" key={assessment.id}><div><strong>{assessment.title}</strong><span>{assessment.durationMinutes} minutes / {assessment.submission?.status.toLowerCase()??"not started"}</span></div>{assessment.submission?.status==="SUBMITTED"?<span className="complete-label">Submitted</span>:assessment.submission?<button type="button" onClick={()=>loadAssessment(application.id,assessment.id)}>Continue</button>:<button type="button" onClick={()=>startAssessment(application.id,assessment.id)}>Start</button>}</div>):<p>No assigned assessments.</p>}</section><section><h3>Offer</h3>{application.offer?<div className="portal-action-row"><div><strong>{application.offer.title}</strong><span>{application.offer.status.toLowerCase()}{application.offer.expiresAt?` / expires ${new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(application.offer.expiresAt))}`:""}</span></div><button type="button" onClick={()=>loadOffer(application.id)}>View</button></div>:<p>No offer is available.</p>}</section></div></article>)}</section>{applications.length===0&&<section className="empty-state compact"><h2>No applications found</h2><p>Your verified account email must match the candidate profile used by the hiring team.</p></section>}
    {openAssessment&&<div className="portal-overlay"><section className="portal-modal assessment-taker" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Timed assessment</p><h2>{openAssessment.assessment.title}</h2><span>{openAssessment.submission?`${Math.ceil(secondsRemaining(openAssessment.submission.startedAt,openAssessment.assessment.durationMinutes)/60)} minutes remaining`:`${openAssessment.assessment.durationMinutes} minutes`}</span></div><button type="button" onClick={()=>setOpenAssessment(null)}>Close</button></header><p>{openAssessment.assessment.instructions}</p><form onSubmit={e=>saveSubmission(e,"DRAFT")}>{openAssessment.assessment.questions.map(q=><fieldset key={q.id}><legend>{q.position}. {q.prompt} <span>{q.points} points</span></legend>{q.language&&<small>{q.language}</small>}{q.starterCode&&<pre>{q.starterCode}</pre>}<label>Your answer<textarea className="code-answer" name={q.id} required maxLength={100000} defaultValue={openAssessment.submission?.answersJson[q.id]??""}/></label></fieldset>)}<p className="portal-code-note">Answers are stored as text. EvidenceHire does not compile or execute your code.</p><div><button className="button secondary" type="submit" disabled={Boolean(busy)||openAssessment.submission?.status==="SUBMITTED"}>Save draft</button><button className="button primary" type="button" disabled={Boolean(busy)||openAssessment.submission?.status==="SUBMITTED"} onClick={e=>saveSubmission({preventDefault:()=>{},currentTarget:(e.currentTarget.closest("form") as HTMLFormElement)} as FormEvent<HTMLFormElement>,"SUBMITTED")}>Submit final answers</button></div></form></section></div>}
    {openOffer&&<div className="portal-overlay"><section className="portal-modal offer-view" role="dialog" aria-modal="true"><header><div><p className="eyebrow">Offer</p><h2>{openOffer.offer.title}</h2><span>{openOffer.offer.status.toLowerCase()}</span></div><button type="button" onClick={()=>setOpenOffer(null)}>Close</button></header><div className="offer-copy"><p>{openOffer.offer.details}</p>{openOffer.offer.compensationDetails&&<section><h3>Compensation</h3><p>{openOffer.offer.compensationDetails}</p></section>}{openOffer.offer.expiresAt&&<small>Respond by {new Intl.DateTimeFormat("en",{dateStyle:"long"}).format(new Date(openOffer.offer.expiresAt))}</small>}</div>{openOffer.offer.status==="SENT"&&<form onSubmit={e=>respondOffer(e,"ACCEPTED")}><label>Response note <span className="optional">Optional</span><textarea name="responseNote" maxLength={5000}/></label><div><button className="button secondary" type="button" onClick={e=>respondOffer({preventDefault:()=>{},currentTarget:(e.currentTarget.closest("form") as HTMLFormElement)} as FormEvent<HTMLFormElement>,"DECLINED")}>Decline</button><button className="button primary" type="submit">Accept offer</button></div></form>}</section></div>}
  </main>;
}
