-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CANDIDATE', 'RECRUITER', 'HIRING_MANAGER', 'INTERVIEWER', 'ADMIN');

-- AlterTable
ALTER TABLE "Membership" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'CANDIDATE';
